### ISSUE TITLE
Error Upon Launch [LIS REMASTERED]

### ISSUE THREAD

**Issue by XeX8Emily** [TrevTV/DawnVR#12]
it keeps saying "Initalization Error" even though i followed the tutorial on how to fix this issue

**Comment by fremdev** [comment]
> it keeps saying "Initalization Error" even though i followed the tutorial on how to fix this issue

@XeX8Emily Downgrade to MelonLoader 0.57. It looks like it doesn't work with the latest (0.61)

**Comment by TrevTV** [comment]
I haven't updated this for the changes in 0.6.1, updated the README to mention that
