### ISSUE TITLE
 [DawnVR] [ERROR] [SteamVR] Initialization failure! Disabling VR modules.

### ISSUE THREAD

**Issue by GuiOliv** [TrevTV/DawnVR#13]
I installed everything right twice and, although the game loads, it doesn't show up on my Quest 2 (using AirLink) and the console shows this:

[23:05:11.674] [DawnVR] [WARNING] [SteamVR] Initialization failed. VR may be disabled in player settings. Go to player settings in the editor and check the 'Virtual Reality Supported' checkbox'. OpenVR is not in your list of supported virtual reality SDKs. Add it to the list in player settings. To force OpenVR initialization call SteamVR.Initialize(true).
[23:05:11.676] [DawnVR] [ERROR] [SteamVR] Initialization failure! Disabling VR modules.

**Comment by TrevTV** [comment]
Have you tried the things listed in the FAQ?
https://github.com/TrevTV/DawnVR#i-am-receiving-a-initalization-error-in-the-console-on-startup

**Comment by GuiOliv** [comment]
> Have you tried the things listed in the FAQ? https://github.com/TrevTV/DawnVR#i-am-receiving-a-initalization-error-in-the-console-on-startup

Yes but it did not work

**Comment by TrevTV** [comment]
Did you install the DawnVREnabler/is it showing and running in the ML console? Is it throwing an error? A full log would be better than just the 2 errors

**Comment by GuiOliv** [comment]
> Did you install the DawnVREnabler/is it showing and running in the ML console? Is it throwing an error? A full log would be better than just the 2 errors

Here you go. 
[Latest.log](https://github.com/TrevTV/DawnVR/files/11521087/Latest.log)

As far as I know, everything is installed

**Comment by TrevTV** [comment]
Upgrade MelonLoader to 0.5.7

**Comment by GuiOliv** [comment]
> Upgrade MelonLoader to 0.5.7

Exact same outcome. Would not load in VR

**Comment by TrevTV** [comment]
You might need to delete the globalgamemanager.bak again and/or verify game files

**Comment by GuiOliv** [comment]
> You might need to delete the globalgamemanager.bak again and/or verify game files

I also did that but it didn't work.
The game opens fine on the PC but on the VR it bricks the steamVR view

**Comment by TrevTV** [comment]
The only other thing I can think of is your antivirus or something preventing the mod from replacing the file, other than that would probably just have to be user error that I can't really diagnose
