### ISSUE TITLE
[ERROR] Failed to Invoke PreStart Method!

### ISSUE THREAD

**Issue by 15rf** [TrevTV/DawnVR#16]
Whenever I patch any game and launch it I stare at the unity loading screen for 5 minutes then crash. Im not using any mods. 
If you need more info just tell me.

Log file:

https://cdn.discordapp.com/attachments/1161174173419323452/1161314143211626546/message.txt?ex=6537d913&is=65256413&hm=be311536f8bc66dbbbb88e7cf177243c5b391c93fef3195c861fb72411dbaad0&

**Comment by TrevTV** [comment]
This is not the LemonLoader repository

**Comment by 15rf** [comment]
crap my bad
