### ISSUE TITLE
VR not triggered (Pimax, Index controllers)

### ISSUE THREAD

**Issue by BrziJoe** [TrevTV/DawnVR#9]
Hi. I try several time to open game in vr, but not successful.

First was game install: Life is strange - Before the storm.
The mod is installed (unzipped, version v0.2.1 Beta Latest) directly to game folder, where game exe is. 
3 new folders are added (overwriting existing):
**********************
- Life is Strange - Before the Storm_Data
-  Mods
- Plugins
**********************
I made start option in steam: -vrmode OpenVR
Theater mode is unchecked.

Starting from Steam (not from shortcuts)

The game is starting on monitor only. And even there I can not start Episode 1 (double clicking, and nothing..)
I let it go like that for 15min, but nothing.

I reinstalled all twice.
What should I do?

**Comment by TrevTV** [comment]
Could you please upload `Life is Strange - Before the Storm/MelonLoader/Latest.log`

**Comment by BrziJoe** [comment]
Didn't use Melonloader, just direct extract. I was thinking that was enough...
A new try with Melonloader, and everything works!
Thank you for this mod, it is excellent! :)

You may close this issue, thx.
